FROM python:3.11-alpine

# Instalar dependencias básicas
RUN pip install boto3

# Crear directorio de trabajo
WORKDIR /setup

# Copiar script de configuración
COPY minio-setup-python.py .

# Comando por defecto
CMD ["python", "minio-setup-python.py"]
