# Docker Compose Override para Desarrollo
# Este archivo extiende docker-compose.yml con configuraciones específicas para desarrollo

services:
  # API con configuración extendida para desarrollo
  doc-restoration-api:
    environment:
      # Configuración adicional de desarrollo
      RELOAD_DIRS: "/app/api,/app/src,/app/config"
      RELOAD_EXCLUDES: "__pycache__,*.pyc,*.pyo"
      LOG_LEVEL: debug
      ENABLE_PROFILING: "true"
    command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/app/api", "--reload-dir", "/app/src", "--reload-dir", "/app/config", "--log-level", "debug"]

  # Worker con configuración extendida para desarrollo  
  job-worker:
    environment:
      # Variables adicionales para debugging
      WORKER_DEBUG: "true"
      LOG_LEVEL: debug
      RELOAD_ON_CHANGE: "true"
